<?php

namespace ContainerBEog4g7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3xuwo5mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3xuwo5m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3xuwo5m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'flashy' => ['services', 'mercuryseries_flashy.flashy_notifier', 'getMercuryseriesFlashy_FlashyNotifierService', true],
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'flashy' => '?',
            'postRepository' => 'App\\Repository\\PostRepository',
            'slugger' => '?',
        ]);
    }
}
