<?php

namespace ContainerBEog4g7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FeRYTn6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FeRYTn6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FeRYTn6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaire' => ['privates', '.errored..service_locator.FeRYTn6.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.FeRYTn6": it references class "App\\Entity\\Commentaire" but no such service exists.'],
        ], [
            'commentaire' => 'App\\Entity\\Commentaire',
        ]);
    }
}
