<?php

namespace ContainerIx9dxbx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O9mtlqWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o9mtlqW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o9mtlqW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaire' => ['privates', '.errored..service_locator.o9mtlqW.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.o9mtlqW": it references class "App\\Entity\\Commentaire" but no such service exists.'],
            'commentaireRepository' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
        ], [
            'commentaire' => 'App\\Entity\\Commentaire',
            'commentaireRepository' => 'App\\Repository\\CommentaireRepository',
        ]);
    }
}
