<?php

namespace ContainerIx9dxbx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P90iqv8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p90iqv8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p90iqv8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaire' => ['privates', '.errored..service_locator.p90iqv8.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.p90iqv8": it references class "App\\Entity\\Commentaire" but no such service exists.'],
            'commentaireRepository' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
            'rep' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
        ], [
            'commentaire' => 'App\\Entity\\Commentaire',
            'commentaireRepository' => 'App\\Repository\\CommentaireRepository',
            'rep' => 'App\\Repository\\PostRepository',
        ]);
    }
}
