<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \App\Entity\Post implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'sujet', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'nbrJaime', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'nomUser', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'dateP', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'communaute', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'analysePo', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'liked', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'badlevel', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'Commentaires'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'sujet', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'nbrJaime', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'nomUser', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'dateP', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'communaute', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'analysePo', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'liked', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'badlevel', '' . "\0" . 'App\\Entity\\Post' . "\0" . 'Commentaires'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Post $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSujet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSujet', []);

        return parent::getSujet();
    }

    /**
     * {@inheritDoc}
     */
    public function setSujet(string $sujet): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSujet', [$sujet]);

        return parent::setSujet($sujet);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrJaime(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrJaime', []);

        return parent::getNbrJaime();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrJaime(int $nbrJaime): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrJaime', [$nbrJaime]);

        return parent::setNbrJaime($nbrJaime);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(?string $image): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomUser(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomUser', []);

        return parent::getNomUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomUser(string $nomUser): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomUser', [$nomUser]);

        return parent::setNomUser($nomUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateP(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateP', []);

        return parent::getDateP();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateP(\DateTimeInterface $dateP): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateP', [$dateP]);

        return parent::setDateP($dateP);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommunaute(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommunaute', []);

        return parent::getCommunaute();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommunaute(string $communaute): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommunaute', [$communaute]);

        return parent::setCommunaute($communaute);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnalysePo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnalysePo', []);

        return parent::getAnalysePo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnalysePo(?string $analysePo): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnalysePo', [$analysePo]);

        return parent::setAnalysePo($analysePo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLiked(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLiked', []);

        return parent::getLiked();
    }

    /**
     * {@inheritDoc}
     */
    public function setLiked(?int $liked): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLiked', [$liked]);

        return parent::setLiked($liked);
    }

    /**
     * {@inheritDoc}
     */
    public function getBadlevel(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBadlevel', []);

        return parent::getBadlevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setBadlevel(?int $badlevel): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBadlevel', [$badlevel]);

        return parent::setBadlevel($badlevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', []);

        return parent::getCommentaires();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentaire(\App\Entity\Commentaire $commentaire): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentaire', [$commentaire]);

        return parent::addCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommentaire(\App\Entity\Commentaire $commentaire): \App\Entity\Post
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommentaire', [$commentaire]);

        return parent::removeCommentaire($commentaire);
    }

}
