<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBEog4g7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBEog4g7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBEog4g7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBEog4g7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBEog4g7\App_KernelDevDebugContainer([
    'container.build_hash' => 'BEog4g7',
    'container.build_id' => '51e722a8',
    'container.build_time' => 1682356052,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBEog4g7');
